# Generated by Django 2.2.8 on 2020-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Mens Shirt'), ('WA', 'Women Dress'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('E', 'Electronics'), ('C', 'Computing devices'), ('N', 'Network devices'), ('F', 'Furniture'), ('FB', 'Food and Beverages'), ('U', 'Utensils')], max_length=2),
        ),
    ]
