# Generated by Django 2.2.8 on 2020-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='on_click_purchasing',
            field=models.BooleanField(default=False),
        ),
    ]
