# Generated by Django 2.2.8 on 2020-03-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200323_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
